# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

SMTP_HOST: "cgmeetupdev.herokuapp.com"
DATABASE_NAME: 'cgmeetup_development'
DB_USER_NAME: 'cgmeetup'
DB_PASSWORD: '123456'
SMTP_ADDRESS: 'smtp.sendgrid.net'
SMTP_DOMAIN: 'cgmeetupdev.herokuapp.com'
SMTP_USERNAME: 'NitinBr'
SMTP_PASSWORD: 'Champ@123'
SUPER_ADMIN_EMAIL: 'nitin.singh@brsoftech.org'

DEFAULT_FROM_EMAIL: 'info@cgmeetup.com'
FB_APP_ID: "594255860733170"

development:
  HOST_URL: "http://192.168.1.41:3000"
production:
  HOST_URL: "http://cgmeetupdev.herokuapp.com"
