# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f59c174c2eabe6baa4c98591c49e4d55f3f10b35e1ace1149a6b5b12beabba65db88b53575973bc632e23797e1eafc9ad13806f24609a6629995e56505387f42
  
  paypal_host: https://www.sandbox.paypal.com
  #app_host: http://192.168.1.27:3000/
  app_host:  http://cgmeetupdev.herokuapp.com/
  business_paypal_id: deepak.sharma@brsoftech.org

test:
  secret_key_base: 8a14442c9b3244cc3d90f7da3bddc4989a2b04dba391b84eb109c1ac77b3251c772d14b0c94e62c92f3fdf2a74a3cd8f50cbc72316e656091fae4d047f0d37ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  paypal_host: https://www.sandbox.paypal.com	
  #paypal_host: https://www.paypal.com
  #app_host: http://192.168.1.27:3000/
  app_host: http://cgmeetupdev.herokuapp.com/
 
  
  business_paypal_id: deepak.sharma@brsoftech.org
