# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9febc31ec93f47f2f28861e442882986a656aa2293cf46684bbebc6695b6e66a0fbbd5941ab498114d90f8867618aa787ac2bad1e7552f63a868acd62e94d7a0

test:
  secret_key_base: 05f14780afe1a4e5b56c684f430eac504457e533da43c71a094e1b9eea61e50967244a1ac386b6999873aa23e0cb6b9534b686bf2432ee5697a5afb39a23f34d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
